// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
)

type Task struct {
	ID        int64
	Title     string
	Completed int64
	CreatedAt sql.NullTime
}
